### ISSUE TITLE
/bin/bash: /root/sources/docker.sh: Permission denied

### ISSUE THREAD

**Issue by jasondgreene** [inspircd/inspircd-packages#4]
I'm running into the following issue?

[root@localhost inspircd-packages]# ./build.sh
Building the RPM packages ...
Building the RPM package for CentOS 7 ...
Trying to pull repository docker.io/library/centos ...
7: Pulling from docker.io/library/centos
Digest: sha256:4a701376d03f6b39b8c2a8f4a8e499441b0d567f9ab9d58e4991de4472fb813c
Status: Image is up to date for docker.io/centos:7
/bin/bash: /root/sources/docker.sh: Permission denied

**Comment by sadiepowell** [comment]
i can't reproduce this. What is the host OS and what Docker version are you using?

**Comment by jasondgreene** [comment]
CentOS Linux release 7.8.2003 (Core)
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-161.git64e9980.el7_8.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Tue Apr 28 14:43:01 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-161.git64e9980.el7_8.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Tue Apr 28 14:43:01 2020
 OS/Arch:         linux/amd64
 Experimental:    false

Thank you for the help.

**Comment by sadiepowell** [comment]
I'm guessing your version of Docker is too old? Try running it on a newer system.

**Comment by jasondgreene** [comment]
I now have Docker Version 19.03.8 which fixed the previous error. Now, I'm getting a new error during the build:
dwz: ./usr/lib/inspircd/m_sasl.so.debug: Invalid DW_AT_decl_file file number 1
dwz: Too few files for multifile optimization
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 195 CRC32s did match.
0 blocks
+ '[' '%{buildarch}' = noarch ']'
+ QA_CHECK_RPATHS=1
+ case "${QA_CHECK_RPATHS:-}" in
+ /usr/lib/rpm/check-rpaths
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: inspircd-3.6.0-1.el7.x86_64


RPM build errors:
error: File not found: /root/rpmbuild/BUILDROOT/inspircd-3.6.0-1.el7.x86_64/usr/share/inspircd/.gdbargs
    File not found: /root/rpmbuild/BUILDROOT/inspircd-3.6.0-1.el7.x86_64/usr/share/inspircd/.gdbargs

**Comment by sadiepowell** [comment]
Run `git pull` to update the package sources. I fixed that the other day.

**Comment by jasondgreene** [comment]
Success! Thanks again for the help.

ls -1
index.html
inspircd-3.6.0-1.el7.src.rpm
inspircd-3.6.0-1.el7.x86_64.rpm
inspircd-3.6.0-1.el8.src.rpm
inspircd-3.6.0-1.el8.x86_64.rpm
inspircd-debuginfo-3.6.0-1.el7.x86_64.rpm
inspircd-debuginfo-3.6.0-1.el8.x86_64.rpm
inspircd-debugsource-3.6.0-1.el8.x86_64.rpm
packages.yml
